openapi: 3.1.0
info:
  title: Emoji
  description: Needs a description.
paths:
  /emoji.list:
    get:
      tags:
        - emoji
      description: Lists custom emoji for a team.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/emoji.list
      operationId: emoji_list
      parameters:
        - name: token
          in: query
          description: 'Authentication token. Requires scope: `emoji:read`'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: Default success template
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                additionalProperties: true
                description: >-
                  This method either only returns a brief _OK_ response or a
                  verbose schema is not available for this method.
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: Default error template
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: true
                description: >-
                  This method either only returns a brief _not OK_ response or a
                  verbose schema is not available for this method.
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - emoji:read
components:
  schemas: {}
