openapi: 3.1.0
info:
  title: Bots
  description: Needs a description.
paths:
  /bots.info:
    get:
      tags:
        - bots
      description: Gets information about a bot user.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/bots.info
      operationId: bots_info
      parameters:
        - name: token
          in: query
          description: 'Authentication token. Requires scope: `users:read`'
          required: true
          schema:
            type: string
        - name: bot
          in: query
          description: Bot user to get info on
          schema:
            type: string
      responses:
        '200':
          description: When successful, returns bot info by bot ID.
          content:
            application/json:
              schema:
                title: bots.info schema
                required:
                  - bot
                  - ok
                type: object
                properties:
                  bot:
                    type: object
                    additionalProperties: false
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                additionalProperties: false
                description: Schema for successful response from bots.info method
              example:
                bot:
                  app_id: A161CLERW
                  deleted: false
                  icons:
                    image_36: https://...
                    image_48: https://...
                    image_72: https://...
                  id: B061F7JD2
                  name: beforebot
                  updated: 1449272004
                  user_id: U012ABCDEF
                ok: true
        default:
          description: When no bot can be found, it returns an error.
          content:
            application/json:
              schema:
                title: bots.info error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - bot_not_found
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from bots.info method
              example:
                error: bot_not_found
                ok: false
      security:
        - slackAuth:
            - users:read
components:
  schemas: {}
